### ISSUE TITLE
Can't remove row from ACF repeater in admin area

### ISSUE THREAD

**Issue by markslate** [dachcom-digital/acf-yoast-seo-validation#10] opened 2016-05-05 10:55 UTC
I cannot remove a row from a repeater field when I am in the admin area of a page that has the ACF repeater.
Here is the error from inspector.

**Uncaught TypeError: Cannot convert undefined or null to object acf_yoast.js:104 **

Line 104 has the following code from your plugin:
 delete parentContent[$el.attr('data-id')];

This is what I am using:
Wordpress - 4.4.2
ACF Pro - 5.3.7
Yoast - 3.2.4
Dachcom ACF - YOAST SEO Validation - 5.3.2.2

Hope you can help
Mark

**Comment by TimVevida** [comment] 2016-07-07 07:47
I was not able to reproduce this issue (using WP 4.5.3, ACF 5.3.7 and Yoast 3.3.4), but it seems your WordPress version and Yoast version are a bit out of date. Could you update these and check again?

**Comment by TimVevida** [comment] 2016-07-07 07:49
Note: this seems a duplicate of #8.

**Comment by chriswinch** [comment] 2016-07-07 14:03
I'm experiencing this issue with:
WP - 4.5.3
ACF Pro - 5.3.9.2
Yoast - 3.3.4
Dashcom ACF Yoast... - 5.3.2.2

Gif of error below:
![acf-yoast-dashcom-error](https://cloud.githubusercontent.com/assets/2035554/16655790/f1fdc71e-4453-11e6-8e5c-b042a7d48529.gif)

**Comment by TimVevida** [comment] 2016-07-08 07:24
Nice vid. :)

The problem here is that the video element is not supported by this plugin, but is picked up when you try to remove it. When your container (the repeater in this case) does not contain fields that are supported, it is ``null`` in the plugin variable, and this error occurs.
The best solution is to ignore unsupported fields that are removed. I will look into this and propose a PR within a week.

**Comment by chilledmuffin** [comment] 2016-07-08 09:09
My question took so long to be answered I am now using a different plugin

**Closed** 2016-07-08 09:31 UTC

**Comment by TimVevida** [comment] 2016-07-08 09:33
@chilledmuffin Sorry to hear that, my apologies for not looking into this sooner.
This issue is fixed by merging #14.
